#Local code, binaries, pputils library
PREFIX   = $(HOME)/Documents/HeLaZ#write the path to the root of your HeLaZ distrib here
SRCDIR   = $(PREFIX)/src
BINDIR   = $(PREFIX)/bin
OBJDIR   = $(PREFIX)/obj
LIBDIR   = $(PREFIX)/lib
MODDIR   = $(PREFIX)/mod
FMDIR    = $(PREFIX)/FM
FFTW3DIR = /usr/local/fftw3
CHCKPTDIR  = $(PREFIX)/checkpoint

# Naming ideas : HeLaZ, MoNoLiT (Moment Non Linear Torroidal)
