character(len=40) VERSION
character(len=40) BRANCH
character(len=20) AUTHOR
character(len=40) EXECDATE
character(len=40) HOST
parameter (VERSION='15a591a-dirty')
parameter (BRANCH='MPI')
parameter (AUTHOR='ahoffman')
parameter (EXECDATE='Thu Dec 3 10:18:01 CET 2020')
parameter (HOST ='spcpc606')
