character(len=40) VERSION
character(len=40) BRANCH
character(len=20) AUTHOR
character(len=40) EXECDATE
character(len=40) HOST
parameter (VERSION='c4a68c6-dirty')
parameter (BRANCH='kx_pos_plane')
parameter (AUTHOR='ahoffman')
parameter (EXECDATE='Fri Apr 29 17:51:42 CEST 2022')
parameter (HOST ='spcpc606')
