character(len=40) VERSION
character(len=40) BRANCH
character(len=20) AUTHOR
character(len=40) EXECDATE
character(len=40) HOST
parameter (VERSION='8dcebe0-dirty')
parameter (BRANCH='MPI')
parameter (AUTHOR='ahoffman')
parameter (EXECDATE='Fri Nov 27 17:13:58 CET 2020')
parameter (HOST ='spcpc606')
